services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command:
      - tunnel
      - --no-autoupdate
      - --loglevel
      - info
      - run
    environment:
      TUNNEL_TOKEN: "${CLOUDFLARE_TUNNEL_TOKEN}"
    depends_on:
      - app
      - relay
    networks:
      - calltocall_private
