// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckServer():Promise<void>;

export function CreateRoom(arg1:string):Promise<main.MeetingSession>;

export function JoinRoom(arg1:main.JoinRequest):Promise<main.MeetingSession>;
