// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckServer() {
  return window['go']['main']['App']['CheckServer']();
}

export function CreateRoom(arg1) {
  return window['go']['main']['App']['CreateRoom'](arg1);
}

export function JoinRoom(arg1) {
  return window['go']['main']['App']['JoinRoom'](arg1);
}
